//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grocery.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch_master
    {
        public string branchid { get; set; }
        public string branchname { get; set; }
        public string location { get; set; }
        public string Address { get; set; }
        public string contactperson { get; set; }
        public string trnNo { get; set; }
        public string shopnameL1 { get; set; }
        public string shopnameL2 { get; set; }
    }
}
